<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Demo: Hypothesis Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="stats-demo-2_files/libs/clipboard/clipboard.min.js"></script>
<script src="stats-demo-2_files/libs/quarto-html/quarto.js"></script>
<script src="stats-demo-2_files/libs/quarto-html/popper.min.js"></script>
<script src="stats-demo-2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stats-demo-2_files/libs/quarto-html/anchor.min.js"></script>
<link href="stats-demo-2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stats-demo-2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stats-demo-2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stats-demo-2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stats-demo-2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="stats-demo-2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Demo: Hypothesis Testing</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Hypothesis testing is anything you might usually think of as “results.” Essentially: <em>do these data suggest some kind of non-random pattern?</em> The best hypothesis test to use will depend on a few factors, most significantly the data type of the independent (predictor) and dependent (outcome) variables.</p>
<p>This flowchart is a quick-and-dirty, imperfect cheatsheet:</p>
<p><img src="images/StatsFlowChart.png" class="img-fluid"> <!-- By including this image directly in the R Markdown (rather than in a code chunk), it will not be treated as a "Figure". It won't have a label, won't be numbered, won't be listed in a figure list, can't be referenced, etc. --></p>
<p>Here, in Part 2 of the statistics demo, we’ll continue using the <code>starwars</code> dataset to review some of the most common hypothesis tests used in psychology and other social sciences. Specifically, we’ll cover <span class="math inline">\(t\)</span>-tests, ANOVA, chi-square, and linear and logistic regression.</p>
<p>It’s worth noting up top that for common stats like these, there are many ways to do the same thing in R. I’ll show you the way I think is most straightforward, but you may find other packages or functions that you prefer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use built-in dataset 'starwars' for analysis</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sw.desc <span class="ot">&lt;-</span> starwars <span class="sc">%&gt;%</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(height, mass) <span class="sc">%&gt;%</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="co"># or include the `na.rm=T` argument in your measures functions</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a long version to use for dplyr and ggplot stuff later</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sw.desc.long <span class="ot">&lt;-</span> sw.desc <span class="sc">%&gt;%</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(height, mass), <span class="at">names_to =</span> <span class="st">"measure"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictors">Categorical Predictors</h2>
<section id="students-t-tests" class="level3">
<h3 class="anchored" data-anchor-id="students-t-tests">Student’s t-tests</h3>
<p>Student’s<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <span class="math inline">\(t\)</span>-test is the bread and butter of hypothesis testing. It’s used to determine whether there is a significant difference between the means of two groups. They are commonly used to compare the means of a continuous dependent variable across two levels of a categorical independent variable.</p>
<section id="sample" class="level4">
<h4 class="anchored" data-anchor-id="sample">1-sample</h4>
<p>A 1-sample <span class="math inline">\(t\)</span>-test tells you the likelihood that the “true” mean of a value is not equal to 0 (or another reasonable, specific alternative).</p>
<blockquote class="blockquote">
<p><strong>Applied example:</strong> A psychologist wants to test whether rates of depression are greater in gradute students than in the general population.</p>
</blockquote>
<p>For example, a 1-sample <span class="math inline">\(t\)</span>-test on the <code>mass</code> variable should return significant results, rejecting the null hypothesis that the true mean is 0. Since mass is necessarily a positive value, it is impossible that the true mean would be 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 1-sample t-test on the mass variable</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sw.desc<span class="sc">$</span>mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sw.desc$mass
t = 4.4109, df = 58, p-value = 4.525e-05
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
  53.15109 141.47264
sample estimates:
mean of x 
 97.31186 </code></pre>
</div>
</div>
<p>With a <span class="math inline">\(t\)</span>-value of 4.411 and a <span class="math inline">\(p\)</span>-value of 0, we can pretty confidently reject the null hypothesis that the true mean mass of all the physical beings in the Star Wars universe is 0.</p>
<p>We can alternatively specify the mean that the null hypothesis should assume. Let’s assume that the <code>starwars</code> dataset contains the mass of literally every character in Star Wars. In that case, the true population mean mass for Star Wars characters is 97.312 kg. We can specify the null/true mean with the <code>mu</code> (<span class="math inline">\(/mu\)</span>) argument.</p>
<p>Is the mean of this sample different than the true mean?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 1-sample t-test on the mass variable with a specified mean</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Here the specified mean is simply the mean of the sample </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (which is the whole population)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sw.desc<span class="sc">$</span>mass, <span class="at">mu=</span><span class="fu">mean</span>(sw.desc<span class="sc">$</span>mass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sw.desc$mass
t = 0, df = 58, p-value = 1
alternative hypothesis: true mean is not equal to 97.31186
95 percent confidence interval:
  53.15109 141.47264
sample estimates:
mean of x 
 97.31186 </code></pre>
</div>
</div>
<p>Obviously not, since the “sample” is what the true mean was calculated on. The <span class="math inline">\(t\)</span>-value is 0 and the <span class="math inline">\(p\)</span>-value is 1. It is literally not possible for the sample mean to be more like the true mean, because the sample mean <em>is</em> the true mean.</p>
<p>That’s not useful, but if we consider the full dataset the true, full population, we can compare a sample to that population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 1-sample t-test on the mass variable with a specified mean</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># slice_sample randomly selects n rows from the df</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(sw.desc, <span class="at">n=</span><span class="dv">15</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(sw.desc<span class="sc">$</span>mass,<span class="at">mu=</span><span class="fu">mean</span>(sw.desc<span class="sc">$</span>mass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  . and sw.desc$mass
t = -3.2264, df = 81.373, p-value = 0.001807
alternative hypothesis: true difference in means is not equal to 97.31186
95 percent confidence interval:
 -32.10151  66.62445
sample estimates:
mean of x mean of y 
114.57333  97.31186 </code></pre>
</div>
</div>
<p>In nearly all cases (depending on your random seed) this will result in rejecting the null hypothesis. Essentially this is showing that there are some values of mass (namely that of one Mr.&nbsp;The-Hutt, with a mass of 1358 kg) that is such an outlier it makes the mean of the full sample not actually representative of the “average”. (This is a case where median might be a better measure measure of center than mean, and a great example of why it’s important to always look at descriptive statistics before inferential stats.) If we get rid of the extreme outlier and use that as the “true” mean, things might look different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new dataset without Jabba the Hutt (anything with mass more </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># than 500% of the median)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sw.desc.nojabba <span class="ot">&lt;-</span> sw.desc <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(mass <span class="sc">&gt;</span> <span class="dv">5</span><span class="sc">*</span><span class="fu">median</span>(mass))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now randomly sampling from the dataframe will usually <em>not</em> be significantly different from that mean. Sometimes it will be though, just because of random variation. Sometimes is will be <em>extremely</em> significantly different. Why?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># notice that only the mu argument uses the dataset without jabba</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(sw.desc, <span class="at">n=</span><span class="dv">25</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(sw.desc<span class="sc">$</span>mass, <span class="at">mu=</span><span class="fu">mean</span>(sw.desc.nojabba<span class="sc">$</span>mass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  . and sw.desc$mass
t = -0.89444, df = 100.33, p-value = 0.3732
alternative hypothesis: true difference in means is not equal to 75.57586
95 percent confidence interval:
 -23.1651 112.9494
sample estimates:
mean of x mean of y 
142.20400  97.31186 </code></pre>
</div>
</div>
</section>
<section id="sample-1" class="level4">
<h4 class="anchored" data-anchor-id="sample-1">2-sample</h4>
<p>For 2-sample <span class="math inline">\(t\)</span>-tests, we need to include grouping variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># similar df as before but now with some possible grouping vars</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sw.desc2 <span class="ot">&lt;-</span> starwars <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex, gender, species, homeworld, height, mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While a 1-sample <span class="math inline">\(t\)</span>-test compares a sample mean against a static value (like 0), a 2-sample <span class="math inline">\(t\)</span>-test compares two sample means against each other. The null hypothesis of a 2-sample <span class="math inline">\(t\)</span>-test is that the true means of the group are not different.</p>
<blockquote class="blockquote">
<p><strong>Applied example:</strong> A psychologist wants to test whether rates of graduate students’ depression are different in red and blue states<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
</blockquote>
<p>Is the mass of male<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> characters different from female characters?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 2-sample t-test on the mass variable</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># comparing male &amp; female groups</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="do">## overall, sig.</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ttest2_overall <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"male"</span>)<span class="sc">$</span>mass,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"female"</span>)<span class="sc">$</span>mass</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>ttest2_overall</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  filter(sw.desc2, sex == "male")$mass and filter(sw.desc2, sex == "female")$mass
t = 4.8612, df = 43.298, p-value = 1.571e-05
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 14.94106 36.11926
sample estimates:
mean of x mean of y 
 80.21905  54.68889 </code></pre>
</div>
</div>
<p>For all characters, yes. We can reject the null hypothesis that the means are the same (<span class="math inline">\(t\)</span> = 4.861, <span class="math inline">\(p\)</span> &lt; .001).</p>
<p>What if we just look at the humans?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 2-tailed 2-sample t-test on the mass variable, comparing male and female humans only</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ttest2_humans <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"male"</span>, species <span class="sc">==</span> <span class="st">"Human"</span>)<span class="sc">$</span>mass,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"female"</span>, species <span class="sc">==</span> <span class="st">"Human"</span>)<span class="sc">$</span>mass</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ttest2_humans</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  filter(sw.desc2, sex == "male", species == "Human")$mass and filter(sw.desc2, sex == "female", species == "Human")$mass
t = 2.8744, df = 2.7808, p-value = 0.06986
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -4.648771 63.417398
sample estimates:
mean of x mean of y 
 85.71765  56.33333 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Because all humans in the dataset are recorded as 1 of exactly 2 options </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (male or female)</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># we can use a formula syntax instead of specifying the vectors directly</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># This only works if the factor variable has exactly 2 levels!</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># First we create a new dataframe with only humans, to ensure only 2 levels</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>humans_only <span class="ot">&lt;-</span> <span class="fu">filter</span>(sw.desc2, species <span class="sc">==</span> <span class="st">"Human"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use the syntax `dependent_variable ~ independent_variable` </span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># to specify the formula</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ttest2_humans_alt <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  humans_only<span class="sc">$</span>mass <span class="sc">~</span> humans_only<span class="sc">$</span>sex</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For humans, no. We cannot reject the null hypothesis that the means are the same (<span class="math inline">\(t\)</span> = 2.874, <span class="math inline">\(p\)</span> = 0.07).</p>
</section>
<section id="sample-1-tailed" class="level4">
<h4 class="anchored" data-anchor-id="sample-1-tailed">2-sample; 1-tailed</h4>
<p>Often we have a theoretical reason to expect a difference in one direction, especially if we are building on previous research. This is where you can use a 1-tailed <span class="math inline">\(t\)</span>-test.</p>
<blockquote class="blockquote">
<p><strong>Applied example:</strong> A psychologist wants to test whether the rate of graduate students’ depression is higher in red states than blue states. She is interested in explaining why academics are leaving institutions in red states and believes depression may be a factor. While it is possible that depression rates are lower in red states, she has no theoretical basis for expecting academics to leave red states because they were <em>happier</em> there.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</blockquote>
<p>Outside the Star Wars Cinematic Universe, we know that the mean mass of male humans is higher than that of female humans. Rather than looking for <em>any</em> difference in means, we have a theoretical reason to look for a difference in one particular direction. If we set <code>alternative = "greater"</code>, the null hypothesis is that the true difference in means (mean-of-males - mean-of-females) is less than or equal to 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 1-tailed 2-sample t-test on the mass variable, comparing male and female humans</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with the null hypothesis that the *difference* in means is </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># less than or equal to 0</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ttest2_humans_1tail <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the order of the groups is important here!</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"male"</span>, species <span class="sc">==</span> <span class="st">"Human"</span>)<span class="sc">$</span>mass,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sw.desc2, sex <span class="sc">==</span> <span class="st">"female"</span>, species <span class="sc">==</span> <span class="st">"Human"</span>)<span class="sc">$</span>mass,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"greater"</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>ttest2_humans_1tail </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  filter(sw.desc2, sex == "male", species == "Human")$mass and filter(sw.desc2, sex == "female", species == "Human")$mass
t = 2.8744, df = 2.7808, p-value = 0.03493
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 4.533443      Inf
sample estimates:
mean of x mean of y 
 85.71765  56.33333 </code></pre>
</div>
</div>
<p>Now we do see a significant effect. We can reject the null hypothesis that the mean mass of females is greater than or equal to that of males are the same (<span class="math inline">\(t\)</span> = 2.874, <span class="math inline">\(p\)</span> &lt; 0.035).</p>
<p>Notice the importance of ordering in the <code>t.test()</code> function. In this 2-tailed 2-sample <span class="math inline">\(t\)</span>-test, we want to know test whether it’s possible (the null – the thing we <em>don’t</em> expect) that the mean mass of females (group 2) is greater than or equal to the mean mass of males, so we put the group we <em>do</em> expect to be greater first. Try switching the order of the groups in each of the <code>t.test()</code> functions above and see how the results change.</p>
<p>You can use formula syntax for 1-tailed tests as well (as long as there are exactly two levels in the factor variable), but you need to be extra careful about the order of the levels. In this case, the unordered <code>sex</code> variable will put levels in alphabetical order: group 1 will be female and group 2 will be male – the opposite of the previous model.</p>
<p>Now we think that group 2 (males) will have greater mass than group 1 (females). The alternative hypothesis is that the mean mass of group 2 will be <em>less than</em> or equal to the mean mass of group 1. We can use the <code>alternative = "less"</code> argument to specify this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ttest2_humans_1tail_alt <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  humans_only<span class="sc">$</span>mass <span class="sc">~</span> humans_only<span class="sc">$</span>sex,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The alt/null hyp. is that group 2 is *less* than group 1</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"less"</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>ttest2_humans_1tail_alt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  humans_only$mass by humans_only$sex
t = -2.8744, df = 2.7808, p-value = 0.03493
alternative hypothesis: true difference in means between group female and group male is less than 0
95 percent confidence interval:
      -Inf -4.533443
sample estimates:
mean in group female   mean in group male 
            56.33333             85.71765 </code></pre>
</div>
</div>
<p>Compare the two outputs:</p>
<ol type="1">
<li>The <span class="math inline">\(t\)</span>-values are of the same absolute magnitude, but opposite sign (2.874 vs.&nbsp;-2.874). The <span class="math inline">\(t\)</span>-value is calculated based on the difference between the means of the two groups, and the direction of that difference matters.</li>
<li>The <span class="math inline">\(p\)</span>-value is the same in both tests, <span class="math inline">\(p\)</span> <code>apa_p(ttest2_humans_1tail$p.value, add_equals=T)</code>. The <span class="math inline">\(p\)</span>-value is calculated based on the absolute value of the <span class="math inline">\(t\)</span>-value, so the direction of the difference doesn’t matter.</li>
<li>The alternative hypothesis is different in two ways:</li>
<li>Direction of difference</li>
<li>Specificity: formula syntax uses the level names of the factor variable, while the vector syntax simply refers to “the difference in means” without specifying which group is which or the order of inclusion.</li>
<li>The sample estimates are different in the same two ways:</li>
<li>Order of the groups</li>
<li>Specificity: formula syntax uses level names; vector syntax simply uses <code>x</code> and <code>y</code></li>
</ol>
<p>What are the advantages of each?</p>
</section>
<section id="analysis-choice" class="level4">
<h4 class="anchored" data-anchor-id="analysis-choice">Analysis choice</h4>
<p>Take a second here to compare the motivations and results of these two tests. The first test told us that, statistically, there’s no difference between the means of males and females in the SWU. The second test said the opposite: that the mean mass of males is statistically significantly greater than the mean mass of females.</p>
<p>As a scientist, which results are we going to stand behind? The difference in totally fictional mass between male and female humans in the Star Wars Universe is a pretty low stakes interpretation, but the same logic applies to actual real science that matters.</p>
<p>2-tailed tests are generally recommended as the standard choice. They are more conservative (less likely to support a result that doesn’t really exist) and allow for the possibility of a difference in either direction.</p>
<p>1-tailed tests should only be used when 1) you have a specific directional hypothesis <em>and</em> 2) you are completely uninterested in effects in the opposite direction. If you’re not sure, stick with two-tailed tests.</p>
<p>That said, don’t avoid one-tailed tests in the name of “conservatism.” It’s not p-hacking to use a one-tailed test when you have a good reason to do so, it’s just using statistics effectively to answer the specific question you have.</p>
</section>
<section id="optional-arguments" class="level4">
<h4 class="anchored" data-anchor-id="optional-arguments">Optional arguments</h4>
<p>Important optional arguments for <span class="math inline">\(t\)</span>-tests:</p>
<ul>
<li>True mean (<span class="math inline">\(\mu\)</span>): <code>mu</code>
<ul>
<li>In a 1-sample test, the null hypothesis will compare the mean to 0 by default. You can change this to the “true mean”.</li>
</ul></li>
<li>Alt hypothesis: <code>alternative = c("two.sided", "less", "greater")</code>
<ul>
<li>By default this tests that the 1-var mean is not equal to 0 (or <span class="math inline">\(\mu\)</span>) or that the 2-vars means are not equal to each other. If you are specifically looking to demonstrate that the mean is greater than or less than 0 (or <span class="math inline">\(\mu\)</span>) or that one particular group’s mean is greater than the others (e.g., you expect the control group to have poorer outcomes than the treatment/intervention group), set this to <code>less</code> or <code>greater</code>.</li>
</ul></li>
<li>Paired: <code>paired = FALSE</code>
<ul>
<li>If the observations are related in some way, you can use a paired <span class="math inline">\(t\)</span>-test. For example if you want to compare growth between pre-test and post-test, you’re more interested in the change for each individual rather than either mean test score <em>per se</em>.</li>
</ul></li>
<li>Confidence level: <code>conf.level = 0.95</code>
<ul>
<li>Set an alternative confidence interval when comparing means. This is rarely changed; 95% is almost always the expectation here.</li>
</ul></li>
</ul>
</section>
</section>
<section id="anova" class="level3">
<h3 class="anchored" data-anchor-id="anova">ANOVA</h3>
<p>Think of an Analysis of Variance (ANOVA) as an extension of the <span class="math inline">\(t\)</span>-test. With a <span class="math inline">\(t\)</span>-test you can compare the mean of 1 group to a static value or the means of 2 groups to each other. The basic functionality of ANOVA is to allow you compare three or more groups.</p>
<p>ANOVA is a whole family of analyses, but we’ll focus on just 1-way ANOVA and 2-way ANOVA. One-way ANOVA is appropriate when there is one categorical independent variable with multiple levels, while two-way ANOVA is used when there are two categorical independent variables and their interaction effect needs to be examined.</p>
<p>Start by messing with the SW dataset to get it into a form that’s useful for ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sw.hyp <span class="ot">&lt;-</span> starwars <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, height, mass, hair_color, skin_color, eye_color, sex, gender, homeworld, species) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hair_color =</span> <span class="fu">str_remove</span>(hair_color, <span class="st">"[,].*$"</span>),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">eye_color =</span> <span class="fu">str_remove</span>(eye_color, <span class="st">"[,].*$"</span>),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">skin_color =</span> <span class="fu">str_remove</span>(skin_color, <span class="st">"[,].*$"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex3cat =</span> <span class="fu">case_when</span>(sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>) <span class="sc">~</span> sex,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                            <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"other"</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">hair4cat =</span> <span class="fu">case_when</span>(hair_color <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"white"</span>, <span class="st">"grey"</span>) <span class="sc">~</span> <span class="st">"light"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>                              hair_color <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"blond"</span>, <span class="st">"blonde"</span>) <span class="sc">~</span> <span class="st">"blond"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                              hair_color <span class="sc">==</span> <span class="st">"none"</span> <span class="sc">~</span> <span class="st">"none"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>                              <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"dark"</span>),</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">skin6cat =</span> <span class="fu">case_when</span>(skin_color <span class="sc">%in%</span> </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"brown"</span>, <span class="st">"brown mottle"</span>, <span class="st">"dark"</span>, <span class="st">"tan"</span>) </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">~</span> <span class="st">"tan/dark"</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>                              skin_color <span class="sc">%in%</span> </span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"green-tan"</span>, <span class="st">"mottled green"</span>) </span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">~</span> <span class="st">"cool hue"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>                              skin_color <span class="sc">%in%</span> </span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"silver"</span>, <span class="st">"gold"</span>, <span class="st">"metal"</span>) </span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">~</span> <span class="st">"metallic"</span>,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>                              skin_color <span class="sc">%in%</span> </span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"fair"</span>, <span class="st">"light"</span>, <span class="st">"white"</span>) </span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">~</span> <span class="st">"fair/light"</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>                              skin_color <span class="sc">%in%</span> </span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"yellow"</span>, <span class="st">"red"</span>, <span class="st">"orange"</span>) </span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">~</span> <span class="st">"warm hue"</span>,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>                              <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"other"</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>                              ),</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">species3cat =</span> <span class="fu">ifelse</span>(species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Human"</span>, <span class="st">"Droid"</span>), </span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>                              species, <span class="st">"Other"</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># let's also drop jabba</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(name <span class="sc">!=</span> <span class="st">"Jabba Desilijic Tiure"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="way-anova" class="level4">
<h4 class="anchored" data-anchor-id="way-anova">1-Way ANOVA</h4>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist wants to compare the effectiveness of three different stress reduction techniques (e.g., mindfulness meditation, progressive muscle relaxation, and deep breathing exercises) on reducing anxiety levels among participants.</p>
</blockquote>
<p>One-way ANOVA can be used to test for significant differences in anxiety levels (dependent variable, continuous) across the three stress reduction techniques (independent variable, factor).</p>
<p>If the <span class="math inline">\(p\)</span>-value from the ANOVA test is significant, post-hoc tests (e.g., Tukey’s HSD) can be conducted to determine which techniques differ significantly from each other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 1-way ANOVA comparing the dependent variable (height) across</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># levels of the independent factor variable (sex3cat)</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>anova_sex3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(height <span class="sc">~</span> sex3cat, <span class="at">data=</span>sw.hyp)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_sex3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
sex3cat      2   6450    3225    2.75 0.0702 .
Residuals   77  90290    1173                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
6 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova_sex3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = height ~ sex3cat, data = sw.hyp)

$sex3cat
                   diff       lwr        upr     p adj
male-female    7.551378 -16.85897 31.9617284 0.7409512
other-female -20.904762 -55.86907 14.0595448 0.3312404
other-male   -28.456140 -57.80962  0.8973373 0.0594073</code></pre>
</div>
</div>
<p>Here there is a trending but non-significant difference in height across the 3 sex categories <span class="math inline">\(F\)</span>() = 2.75, <span class="math inline">\(p\)</span> = 0.07.</p>
<p>Using Tukey post-hoc adjustment we can see this difference is primarily driven by the difference in height between those in the “male” and “other” category.</p>
</section>
<section id="way-anova-1" class="level4">
<h4 class="anchored" data-anchor-id="way-anova-1">2-Way ANOVA</h4>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist conducts a study to investigate the effects of both sex (male vs.&nbsp;female) and stress level (low vs.&nbsp;high) on performance in a cognitive task.</p>
</blockquote>
<p>In this scenario, there are two independent variables: sex (with two levels: male and female) and stress level (with two levels: low and high). The dependent variable is performance in the cognitive task. Two-way ANOVA would be used to assess the main effects of gender and stress level, as well as their interaction effect on performance. The interaction effect indicates whether the effect of one independent variable depends on the level of the other independent variable.</p>
<p>In the Star Wars dataset, we can use a 2-way ANOVA to look for associations between any of the factor variables we’ve already defined (or that existed in the original dataset). For example, is there a relationship between categories of sex and hair color in predicting a character’s height?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 2-way ANOVA comparing the dependent variable (height) </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># across sex and hair color</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>anova_sex3_hair4 <span class="ot">&lt;-</span> <span class="fu">aov</span>(height <span class="sc">~</span> sex3cat <span class="sc">+</span> hair4cat, <span class="at">data=</span>sw.hyp)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_sex3_hair4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
sex3cat      2   6450    3225   2.730 0.0718 .
hair4cat     3   2879     960   0.812 0.4910  
Residuals   74  87411    1181                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
6 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova_sex3_hair4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = height ~ sex3cat + hair4cat, data = sw.hyp)

$sex3cat
                   diff       lwr       upr     p adj
male-female    7.551378 -16.96819 32.070950 0.7426034
other-female -20.904762 -56.02551 14.215990 0.3340873
other-male   -28.456140 -57.94096  1.028677 0.0608330

$hair4cat
                   diff       lwr      upr     p adj
dark-blond    0.6163802 -47.06224 48.29500 0.9999858
light-blond -16.0775689 -76.67604 44.52090 0.8977858
none-blond    7.7114314 -39.89923 55.32209 0.9739036
light-dark  -16.6939492 -59.88228 26.49438 0.7406382
none-dark     7.0950511 -14.34863 28.53873 0.8204713
none-light   23.7890003 -19.32428 66.90228 0.4725622</code></pre>
</div>
</div>
<p>Shockingly, there is no significant difference. Who could have guessed that the powerful combo of hair color and sex together would not predict height?</p>
<p>As another example, let’s look and sex and gender together. It’s a weird combo, but you could come up with a theoretical reason to ask about an interaction here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a 2-way ANOVA comparing the dependent variable (height) across </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sex and gender</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>anova_sex3_gender <span class="ot">&lt;-</span> <span class="fu">aov</span>(height <span class="sc">~</span> sex3cat <span class="sc">+</span> gender, <span class="at">data=</span>sw.hyp)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_sex3_gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
sex3cat      2  10712    5356   4.590 0.0133 *
gender       1   1549    1549   1.327 0.2531  
Residuals   72  84020    1167                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
10 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova_sex3_gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = height ~ sex3cat + gender, data = sw.hyp)

$sex3cat
                   diff       lwr       upr     p adj
male-female    7.551378 -16.83329 31.936048 0.7399418
other-female -40.371429 -82.96234  2.219483 0.0668560
other-male   -47.922807 -86.05244 -9.793179 0.0100171

$gender
                       diff       lwr      upr     p adj
masculine-feminine 2.923716 -16.70214 22.54957 0.7673432</code></pre>
</div>
</div>
<p>In this case, there is one significant main effect (sex category) and no significant interaction effects.</p>
<p>Aside from being used as a hypothesis test itself, another important use for ANOVA is comparing model fit. For example, you create 3 possible regressions to test whether household income and/or proximity to grocery stores affects stress level using one variable, both variables, or both and an interaction effect. Passing these models to the <code>anova()</code> function can tell you which model best explains a predictive effect, so you can move forward just using that model.</p>
<p>We can use the <code>mtcars</code> dataset to show a simple example: Does horsepower and/or weight predict a car’s fuel consumption?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the mtcars dataset</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Predicting mpg (miles per gallon) using horsepower</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>model_hp <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
hp          -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Predicting mpg using horsepower and weight</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>model_hpwt <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data =</span> mtcars)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_hpwt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: Predicting mpg using horsepower, weight, with an interaction effect</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>model_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp<span class="sc">*</span>wt, <span class="at">data =</span> mtcars)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp * wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0632 -1.6491 -0.7362  1.4211  4.5513 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 49.80842    3.60516  13.816 5.01e-14 ***
hp          -0.12010    0.02470  -4.863 4.04e-05 ***
wt          -8.21662    1.26971  -6.471 5.20e-07 ***
hp:wt        0.02785    0.00742   3.753 0.000811 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.153 on 28 degrees of freedom
Multiple R-squared:  0.8848,    Adjusted R-squared:  0.8724 
F-statistic: 71.66 on 3 and 28 DF,  p-value: 2.981e-13</code></pre>
</div>
</div>
<p>All three models show a significant effect of the predictor variable(s). The question becomes which of these to use for the rest of the analyses and in the interpretation of our results. Comparing these models in an ANOVA tells us which model (if any) has a significantly better predictive fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare model fit using ANOVA; anova() function is in the stats package</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">anova</span>(model_hp, model_hpwt, model_int)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View the ANOVA table</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>anova_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ hp
Model 2: mpg ~ hp + wt
Model 3: mpg ~ hp * wt
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     30 447.67                                  
2     29 195.05  1   252.627 54.512 4.856e-08 ***
3     28 129.76  1    65.286 14.088 0.0008108 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-values here indicate whether there is a significant difference in fit between one model and the model that came before it. Assuming significant difference, the best model fit is the one with the lowest residual sum of squares (RSS).</p>
<p>Note that depending on the type of models you’re comparing, you might need to find the lowest value of something else. For example with mixed-effects models you’ll (typically) look for the lowest BIC.</p>
<p>The order of the models in the <code>anova()</code> function matters. The output compares each model’s fit to the one above it. This ANOVA tells us that Model 2 (with both hp and wt) is a better fit than Model 1 (hp only), and that Model 3 (with an interaction effect) is a better fit than Model 2. It’s not directly comparing Model 1 and Model 3, but we can infer that Model 3 is the best fit overall because of how they are ordered.</p>
<p>How should you order them? Typically, you start with the simplest model and go in order of complexity. When “complexity” is hard to compare, you can use theoretical motivation to order them. For example, if two models are the same except they test different interaction effects, ask which interaction effect you think it most likely to actually exist (or be stronger). The more likely you think it is, the later you should test it so you can detect improvement model to model.</p>
</section>
</section>
<section id="chi-square" class="level3">
<h3 class="anchored" data-anchor-id="chi-square">Chi-square</h3>
<p>The Chi-Square Test is used to determine whether there is a significant association between categorical variables. It tests for “independence” (the null hypothesis), where there is no association. You can think of it like a kind of “correlation” between categorical data.</p>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist conducting research on the effectiveness of different therapy interventions for treating phobias wants to examine whether there is a significant association between the type of therapy (exposure therapy, cognitive-behavioral therapy, or relaxation therapy) and the self-reported effectiveness (reduction of symptoms, increase in symptoms, or no change).</p>
</blockquote>
<p>In this scenario, there are two categorical variables (therapy type &amp; symptom change). The experimental design allows for a directional association: sensibly, therapy type is the predictor variable and symptom change is the outcome variable. The null hypothesis of a Chi-sq. test is that there is no association between the two variables. That is, a subject in any of the three therapy groups is equally likely to fall into any of the three outcome groups.</p>
<p>Chi-sq. tests are useful outside of experimental designs as well:</p>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist conducting research on pre-school readiness wants to know if there is an association between parent education level (no college, college, graduate) and child’s reading level (below average, average, above average).</p>
</blockquote>
<p>In this scenario, the psychologist is not manipulating the parent’s education level, but there is still directionality. Since parents have already achieved their education level at the time of measuring child reading level, it would be impossible for the child’s reading level to affect the parent’s education level. Although we cannot say with certainty that a significant association between parent education level and child reading level is causal, we can design the study and models to infer high likelihood of causality (assuming there was in fact an association).</p>
<p>Like with correlation of continuous variables, directionality isn’t required. Amount of time spent outside and amount of time spent with family may be positively correlated, but it’s not clear which would cause the other (if either). There may be a significant association between favorite ice cream flavor and favorite candy flavor, but it’s not clear that one of those is the independent predictor and the other the dependent outcome.</p>
<p>In the Star Wars dataset, we can use chi-sq. to look for associations between any of the factor variables we’ve already defined (or that existed in the original dataset). For example, is there a relationship between sex and hair color?</p>
<p>A contingency table shows the frequency of observations in each possible combination of factor levels:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a contingency table with frequencies of hair-color/sex combos</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>sex_hair_table <span class="ot">&lt;-</span> <span class="fu">table</span>(sw.hyp<span class="sc">$</span>sex3cat, sw.hyp<span class="sc">$</span>hair4cat)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>sex_hair_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         blond dark light none
  female     1    9     1    5
  male       3   24     4   29
  other      0    6     0    4</code></pre>
</div>
</div>
<p>The chi-sq. test compares this contingency table to what we’d expect if the observations were evenly distributed <em>based on the number of observations per level</em> within each variable (i.e., not just dividing the total number of observations up evenly across all cells.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform chi-square test on the contingency table</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The chisq.test() function is in the stats package</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>sex_hair_chi2 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(sex_hair_table)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>sex_hair_chi2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  sex_hair_table
X-squared = 3.3807, df = 6, p-value = 0.7598</code></pre>
</div>
</div>
<p>These results are not significant. We can’t reject the null hypothesis that there is any non-random relationship between sex and hair color. The two could be (shockingly) independent.</p>
<p>What about the relationship between hair color and skin color?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a contingency table with frequencies of hair-color/skin-color</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>skin_hair_table <span class="ot">&lt;-</span> <span class="fu">table</span>(sw.hyp<span class="sc">$</span>skin6cat, sw.hyp<span class="sc">$</span>hair4cat)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>skin_hair_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            
             blond dark light none
  cool hue       0    2     1    9
  fair/light     4   24     2    4
  metallic       0    1     0    2
  other          0    1     2   14
  tan/dark       0    9     0    5
  warm hue       0    2     0    4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform chi-square test on the contingency table</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The chisq.test() function is in the stats package</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>skin_hair_chi2 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(skin_hair_table)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>skin_hair_chi2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  skin_hair_table
X-squared = 40.335, df = 15, p-value = 0.0004035</code></pre>
</div>
</div>
<!-- Note that sometimes in this document whenever I need to include a $p$-value of <.001 in the narrative text I write that out explicitly rather than using a code-reference. That's because if I pulled out the real $p$-value and rounded it, it would usually render as "p<.000", which is not what I want. 

The `papaja` package has a function `apa_p()` that will render a $p$-value according to APA formatting, including rounding and selecting the right equality/comparison operator. You need to add the argument `add_equals=TRUE` to get the `=` or `<` to show up. You can also write your own function for this if you don't want to add in the argument every time or if papaja is giving you problems. -->
<p>In this case, <span class="math inline">\(\chi^2\)</span> = 40.3353563 (<span class="math inline">\(p\)</span> &lt; .001). We can reject the null hypothesis and claim that there is an association between hair and skin color in characters in the Star Wars Universe. We cannot make any claims about direction of the association.</p>
</section>
</section>
<section id="continuous-predictors" class="level2">
<h2 class="anchored" data-anchor-id="continuous-predictors">Continuous Predictors</h2>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>Linear regression models the relationship between a continuous dependent variable and one or more (i.e., multiple regression) independent variables, at least one of which is also continuous. Linear modeling can also incorporate interaction effects between predictors.</p>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist is interested in understanding the relationship between hours of study per week and exam scores among college students. Using a linear regression to model the this relationship shows 1) whether there is a relationship, 2) whether that association is statistically significant, 3) the association’s direction, and 4) the magnitude of the association.</p>
</blockquote>
<p>Since both variables in this case are continuous, the psychologist could have used a correlation instead of a regression. One advantage of the regression is that the magnitude of the effect has more immediate application. Correlation is always normed to be between 0 and 1, so the magnitude of the correlation coefficient can be interpreted as a kind of percentage change.</p>
<p>With regression, the slope (magnitude) is not normed and applies directly to the variables. It can be interpreted as change-in-outcome per change-in-predictor, i.e.&nbsp;the expected change (probably increase?) in exam score for every additional hour of studying. Without norming, the regression will also give an intercept, which tells you what the predicted value of <span class="math inline">\(y\)</span> would be if <span class="math inline">\(x=0\)</span> (i.e., the expected exam score for someone who did not study at all).</p>
<p>Another advantage of linear models is the opportunity to consider multiple predictor variables. Additional independent variables may be variables of interest (maybe both study hours and sleep hours affect exam scores) or one may be a control (maybe the effect of study hours differs based on students’ pre-test scores).</p>
<p>In the Star Wars dataset, we can use linear regression to model the relationship between mass and height, like we did with correlation (in the descriptive stats demo).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># recall the correlation of mass and height from above</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>mass_height_corr <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(sw.desc<span class="sc">$</span>mass, sw.desc<span class="sc">$</span>height)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>mass_height_corr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sw.desc$mass and sw.desc$height
t = 0.99653, df = 57, p-value = 0.3232
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.1295651  0.3743950
sample estimates:
     cor 
0.130859 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model the effect of height on mass</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the formula here is in the syntax [outcome var] ~ [predictor var]</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>mass_height_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass <span class="sc">~</span> height, <span class="at">data =</span> sw.desc)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the output of the model object itself doesn't have a lot of info</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># so you'll want to look at the summary() of the model</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>summary_mass_height_lm <span class="ot">&lt;-</span> <span class="fu">summary</span>(mass_height_lm)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>summary_mass_height_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass ~ height, data = sw.desc)

Residuals:
    Min      1Q  Median      3Q     Max 
 -60.95  -29.51  -20.83  -17.65 1260.29 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -11.4868   111.3842  -0.103    0.918
height        0.6240     0.6262   0.997    0.323

Residual standard error: 169.5 on 57 degrees of freedom
Multiple R-squared:  0.01712,   Adjusted R-squared:  -0.0001194 
F-statistic: 0.9931 on 1 and 57 DF,  p-value: 0.3232</code></pre>
</div>
</div>
<p>The correlation between height and mass shows that there is some positive association: as height increases, mass increases too (though remember from the correlation matrix that this effect was not significant).</p>
<p>The linear model shows that for every additional unit of height (cm), mass increases by 0.6240033 units (kg), <em>but</em> this effect is not significant.</p>
<p>One clear way to see that this very simple regression is doing basically the same thing as the correlation is comparing the <span class="math inline">\(p\)</span>-values of the <code>cor.test</code> and of the <code>height</code> slope. You can find these in the output, or extract them from the objects:</p>
<ul>
<li>Correlation: <span class="math inline">\(p\)</span> = 0.3232031</li>
<li>Regression: <span class="math inline">\(p\)</span> = 0.3232031</li>
</ul>
<p>The lm also gives an intercept, which in this case is a fantastic example of when the intercept is simply not a useful thing to interpret: what should we expect the mass of a 0cm being to be? Apparently -11.4868157, which is nonsensical. First of all, mass cannot be negative, but that could potentially just be the result of a bad model fit. More clearly, a being cannot exist with literally 0 height. If a real observation’s predictor measurement <em>can literally never be 0</em>, the intercept does not have a meaningful interpretation. It’s still important for the model’s overall functionality and fit, but only the slope will go into our interpretation of the results.</p>
<p><strong>Be careful: the intercept will have its own significance value!</strong> It’s almost always the significance of the <em>slope</em> that matters, so don’t get excited when you see <code>***</code> on the intercept line of the model output.</p>
<p>As discussed above, visualizing simple regression is the same as visualizing correlation: scatter plot and linear smoothing (<a href="#fig-visualize-regression-mass-height" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sw.hyp, <span class="fu">aes</span>(<span class="at">x=</span>height, <span class="at">y=</span>mass)) <span class="sc">+</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-visualize-regression-mass-height" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-visualize-regression-mass-height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-visualize-regression-mass-height-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-visualize-regression-mass-height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Visualize simple regression of mass by height
</figcaption>
</figure>
</div>
</div>
</div>
<p>Multiple regression works exactly the same way. Add predictor or control variables to the right side of the formula. Connect them with an asterisk to look for an interaction effect.</p>
<p>Using the <code>mtcars</code> dataset, (how) do horsepower and displacement predict fuel efficiency (miles per gallon)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The formula syntax for regressions (and nearly all modelling in R) is:</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 outcome variable on the left of a tilde ~</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># all individual predictor variables (including controls) separated by </span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plus signs + to the right of the tilde ~</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co"># after individual vars, any interaction effects are included by using </span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># an asterisk * between the vars</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># [outcome var] ~ [predictor var 1] + [predictor var 2] + ... + [predictor var 1]*[predictor var 2]</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>cars_hp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> mtcars, mpg <span class="sc">~</span> hp)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cars_hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
hp          -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>cars_hp_disp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> mtcars, mpg <span class="sc">~</span> hp <span class="sc">+</span> disp)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cars_hp_disp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + disp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7945 -2.3036 -0.8246  1.8582  6.9363 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.735904   1.331566  23.083  &lt; 2e-16 ***
hp          -0.024840   0.013385  -1.856 0.073679 .  
disp        -0.030346   0.007405  -4.098 0.000306 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.127 on 29 degrees of freedom
Multiple R-squared:  0.7482,    Adjusted R-squared:  0.7309 
F-statistic: 43.09 on 2 and 29 DF,  p-value: 2.062e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>cars_inter <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> mtcars, mpg <span class="sc">~</span> hp <span class="sc">+</span> disp <span class="sc">+</span> hp<span class="sc">*</span>disp)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cars_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + disp + hp * disp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5153 -1.6315 -0.6346  0.9038  5.7030 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.967e+01  2.914e+00  13.614 7.18e-14 ***
hp          -9.789e-02  2.474e-02  -3.956 0.000473 ***
disp        -7.337e-02  1.439e-02  -5.100 2.11e-05 ***
hp:disp      2.900e-04  8.694e-05   3.336 0.002407 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.692 on 28 degrees of freedom
Multiple R-squared:  0.8198,    Adjusted R-squared:  0.8005 
F-statistic: 42.48 on 3 and 28 DF,  p-value: 1.499e-10</code></pre>
</div>
</div>
<!-- In this section I use the coefficients() or coef() (same exact thing) function to extract slope. This function makes it very easy to reference the intercept and slope of a linear regression. -->
<p>In Model 1, which includes just one independent variable (<code>mpg ~ hp</code>), horsepower is negatively associated with fuel efficiency (<span class="math inline">\(\beta\)</span> = -0.068, <span class="math inline">\(p\)</span> &lt; .001). That is, for every additional unit of horsepower we expect a reduction of 0.068 mpg.</p>
<!-- In this section I am using a different method to reference the coefficients and $p$-values from the model. The `tidy()` function in the `broom` package will produce a simple table to quickly reference the most commonly needed values from (most) models. I also use the apa_p() function from papaja. -->
<p>Model 2 includes a second (continuous) predictor variable: displacement. In this regression, displacement (<span class="math inline">\(\beta\)</span> = -0.03, <span class="math inline">\(p\)</span> &lt; .001) is a better predictor of mpg than horsepower, which in fact is no longer even significant (<span class="math inline">\(\beta\)</span> = -0.03, <span class="math inline">\(p\)</span> &lt; = .074).</p>
<p>Model 3 adds a potential interaction effect between horsepower and displacement. In this example, an interaction would mean that the strength of the effect on mpg of horsepower changes across changing levels of displacement. (As a simple psychology example, we might be interested in the interaction of age and sleep deprivation on exam scores. Sleep deprivation will probably lower exam scores for everyone, but it might lower them <em>a lot</em> for younger kids and just a little for older kids or vice versa). In this model, both horsepower and displacement have a significant effect on mpg, <em>and</em> there is a significant interaction effect (<span class="math inline">\(\beta\)</span> = 0, <span class="math inline">\(p\)</span> .002). The effect of displacement on mpg gets stronger as horsepower increases, above and beyond overall effects of displacement and horsepower.</p>
<p><em>If we have multiple reasonable models that give different results, which one should we use?</em> We definitely don’t want to create a bunch of models and pick the one that gives us the results we like the best. Instead, remember that ANOVA can compare model fit to help us make an informed and (relatively) impartial choice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare model fit using ANOVA</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>cars.aov <span class="ot">&lt;-</span> <span class="fu">anova</span>(cars_hp, cars_hp_disp, cars_inter)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>tidy.cars.aov <span class="ot">&lt;-</span> <span class="fu">tidy</span>(cars.aov)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>cars.aov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ hp
Model 2: mpg ~ hp + disp
Model 3: mpg ~ hp + disp + hp * disp
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     30 447.67                                  
2     29 283.49  1   164.181 22.662 5.339e-05 ***
3     28 202.86  1    80.635 11.130  0.002407 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We look for the model that has the lowest residual sum of squares (RSS) <em>that is also</em> significantly improved from the next best model. In this case, Model 2 is a significantly better fit than Model 1 (<span class="math inline">\(p\)</span> &lt; .001), and Model 3 is a significantly better fit than Model 2 (<span class="math inline">\(p\)</span> = .002). Moving forward, it makes sense to use Model 3 that includes the interaction between the two independent variables of interest.</p>
<p>Remember that order matters! Try shuffling the models around and seeing how the output changes.</p>
<section id="visualizing-multiple-regression" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-multiple-regression">Visualizing multiple regression</h4>
<p>Visualizing relationships between more than two continuous variables gets very complicated very quickly. Although there are ways to plot a regression onto three axes (e.g., the <code>plot3D</code> package), it’s not super easy to produce or interpret, and there’s to way to create plot with more than 3 dimensions.</p>
<p>If you only have one continuous independent variable (the others are categorical or logical), you can use grouping strategies. <a href="#fig-viz-mult-reg-one-cont" class="quarto-xref">Figure&nbsp;2</a> demonstrates this approach to show the effects of horsepower, transmission type (<code>am</code>), and engine type (<code>vs</code>) on fuel efficiency using color grouping and faceting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplot and regression line of MPG, HP, engine type, </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and transmission type</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">factor.am =</span> <span class="fu">factor</span>(am),</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">factor.vs =</span> <span class="fu">factor</span>(vs)) <span class="sc">%&gt;%</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg, <span class="at">color=</span>factor.am)) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>) <span class="sc">+</span> </span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(factor.vs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-viz-mult-reg-one-cont" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viz-mult-reg-one-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-viz-mult-reg-one-cont-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viz-mult-reg-one-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: MPG by HP, across engine and transmission type
</figcaption>
</figure>
</div>
</div>
</div>
<p>With multiple continuous predictors, you can use color, transparency, size, etc. to add another dimension without <em>literally</em> adding another dimension. <a href="#fig-viz-mult-reg-two-cont" class="quarto-xref">Figure&nbsp;3</a> again shows horsepower’s primary effect on MPG, while color adds in information about displacement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg)) <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>disp)) <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-viz-mult-reg-two-cont" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viz-mult-reg-two-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-viz-mult-reg-two-cont-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viz-mult-reg-two-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: MPG by HP with 2 additional continuous variables
</figcaption>
</figure>
</div>
</div>
</div>
<p>You can go crazy with even more continuous variables, but you probably shouldn’t (<a href="#fig-viz-mult-reg-four-cont" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg)) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>disp, <span class="at">alpha =</span> wt, <span class="at">size =</span> qsec)) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">caption =</span> <span class="st">"Chaos. Doable, but terrible."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-viz-mult-reg-four-cont" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viz-mult-reg-four-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-viz-mult-reg-four-cont-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viz-mult-reg-four-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: MPG by HP with 4 additional continuous variables (aka chaos)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h3>
<p>Logistic regression is a type of generalized linear modeling (GLM) used when the dependent variable is binary (two categories). It models the probability of the occurrence of an event based on one or more independent variables. You can interpret a logistic regression as the change in probability that an outcome will occur given changes in your predictors.</p>
<blockquote class="blockquote">
<p><strong>Applied Example:</strong> A psychologist is interested in identifying risk factors associated with the presence of anxiety disorders among college students, such as stress levels, sleep quality, and academic performance.</p>
</blockquote>
<p>In this scenario, the outcome is not <em>how much</em> anxiety students experience (however you’d quantify that as a continuous variable), but simply the binary option of has-an-anxiety-disorder or doesn’t-have-an-anxiety-disorder.</p>
<p>Note that this is a good example of where the direction between variables is not certain. In this model, we are treating the presence of an anxiety disorder as the outcome, which implies that the independent variables of stress, sleep, and academic performance are what lead to that diagnosis. While that may be what’s happening, it’s also reasonable to suspect that having an anxiety disorder is actually what leads to stress, sleep disturbance, and changes in academic performance. The logistic regression is still useful even if the cause-and-effect relationship is murky at best, so long as we are cautious and transparent when interpreting the results.</p>
<p>It is typical, but is not strictly necessary, that at least one predictor is continuous. If all predictors are categorical, it may be better to use something like a Chi-square test.</p>
<p>The <code>glm()</code> function in the <code>stats</code> package allows us to run logistic regressions (and other GLMs) with a syntax very similar to linear regression by specifying a distribution “family.” For logistic regression, the “family” is “binomial.” Here, rather than asking how much a change in horsepower will change MPG, we ask whether a change in horsepower changes the probability of a car being in the “High efficiency” category (defined as MPG above the median).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert MPG to a binary variable</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>mt2 <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">highMPG =</span> <span class="fu">ifelse</span>(mpg <span class="sc">&gt;</span> <span class="fu">median</span>(mtcars<span class="sc">$</span>mpg), <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The key here is the `family=binomial` argument!!</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>log_cars <span class="ot">&lt;-</span> <span class="fu">glm</span>(highMPG <span class="sc">~</span> hp, <span class="at">data =</span> mt2, <span class="at">family =</span> binomial)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = highMPG ~ hp, family = binomial, data = mt2)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  7.62119    2.64469   2.882  0.00396 **
hp          -0.05901    0.02114  -2.791  0.00525 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 44.236  on 31  degrees of freedom
Residual deviance: 18.022  on 30  degrees of freedom
AIC: 22.022

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>Unsurprisingly (given what we saw with the linear models), higher horsepower makes it <em>less</em> likely that a car falls in the high efficiency category.</p>
<p>You can visualize logistic regression with point and smooth geoms just like “regular” (Gaussian) regressions. Specify the <code>glm</code> method and set the family to <code>binomial</code> with the syntax used here to produce <a href="#fig-viz-log-reg" class="quarto-xref">Figure&nbsp;5</a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mt2, <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> highMPG)) <span class="sc">+</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"MPG Category likelihood"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-viz-log-reg" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viz-log-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-viz-log-reg-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viz-log-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: A logistic regression, a probabilistic relationship between horsepower and MPG
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that the y-axis goes from 0 to 1 (0% likely to be high-MPG to 100% likely to be high-MPG), and that all values fall either on <span class="math inline">\(y=0\)</span> or <span class="math inline">\(y=1\)</span>.</p>
<p>Alternatively, you could modify the y-axis labels to more clearly communicate what the two categories are (<a href="#fig-viz-log-reg-alt" class="quarto-xref">Figure&nbsp;6</a>). Neither is necessarily better, but the second might be more intuitive to someone who doesn’t know what a logistic regression is, or if the 2 levels in the category don’t have an inherent order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mt2, <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> highMPG)) <span class="sc">+</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low MPG"</span>, <span class="st">"High MPG"</span>)) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"MPG Category likelihood"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-viz-log-reg-alt" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viz-log-reg-alt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stats-demo-2_files/figure-html/fig-viz-log-reg-alt-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viz-log-reg-alt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: A logistic regression, a probabilistic relationship between horsepower and MPG with alternative axes
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="more" class="level1">
<h1>More</h1>
<ul>
<li>Poisson GLM (GLM with <code>family=poisson</code>)
<ul>
<li>used for count/frequency data</li>
<li>e.g., a psychologist wants to determine whether each of 3 intervention options decreases the number of times symptomatic behaviors are used in an observation period</li>
</ul></li>
<li>Generalized Linear Mixed-Effects Models (GLMM)
<ul>
<li>used for nested or hierarchical data, where you need to account for random or spillover effects</li>
<li>e.g., a psychologist want to determine the effectiveness of a teaching intervention. the intervention is administered at classroom level, but measured at the student level. the psychologist includes School ID as a random effect because they expect students will perform similarly to other students in their own school based on many factors unrelated to the intervention</li>
</ul></li>
</ul>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Fun fact: William Sealy Gosset, a chemist at the Guinness brewery, published under the pseudonym “Student” because (allegedly) Guinness didn’t want their competitors to know they were using statistics to improve their product.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For my international friends who have the luxury of not thinking about this all the time, “red states” and “blue states” are American shorthand for states that tend to vote Republican and Democratic, respectively.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>We’re using the <code>sex</code> variable (male/female/other) here because we’re going to be comparing physical/biological characteristics. The starwars dataset also includes a <code>gender</code> variable you can use for more social/identity comparisons (again, within an entirely fictional universe primarily made up of aliens who almost certainly don’t share our conceptualizations of either sex or gender).<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Though Reviewer 2 might note that all graduate students are necessarily masochists, and therefore would indeed travel to blue states for the pain of it.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>